use bevy::{
    app::AppExit,
    prelude::*,
    render::{
        Render, RenderApp, RenderSystems,
        render_resource::{BufferDescriptor, BufferUsages, MapMode, PollType},
        renderer::{RenderDevice, RenderQueue},
        sync_world::MainEntity,
    },
};
use std::sync::{Arc, Mutex};

use tarasaur::{
    Chunk, ChunkPlugin, ChunkPosition, Field, GpuVoxelChunkBuffers, SDFField, VoxelRenderPlugin,
    field::LOD,
};

const CHUNK_SIZE: u32 = 32;

#[derive(Default)]
struct CompactionTestState {
    test_complete: bool,
    active_cell_count: u32,
    max_offset: u32,
}

#[derive(Resource, Clone, Default)]
struct SharedCompactionState(Arc<Mutex<CompactionTestState>>);

fn main() {
    let mut app = App::new();
    let shared_state = SharedCompactionState::default();

    app.add_plugins((DefaultPlugins, VoxelRenderPlugin, ChunkPlugin));
    app.insert_resource(shared_state.clone());

    app.add_systems(Startup, (setup_sphere_chunk, setup_camera));
    app.add_systems(Update, compaction_test_controller);

    if let Some(render_app) = app.get_sub_app_mut(RenderApp) {
        render_app.insert_resource(shared_state);
        render_app.add_systems(
            Render,
            verify_pass2_compaction_results.in_set(RenderSystems::Cleanup),
        );
    }

    println!("🚀 Starting Pass 2 Stream Compaction Integration Test...");
    app.run();
}

fn setup_camera(mut commands: Commands) {
    commands.spawn(Camera3d::default());
}

/// Spawns a chunk populated with a sphere SDF so surface intersections exist
fn setup_sphere_chunk(mut commands: Commands) {
    let lod = LOD::default();
    let mut sdf = SDFField::new(lod);

    let center = Vec3::splat(CHUNK_SIZE as f32 / 2.0);
    let radius = 10.0f32;

    for z in 0..CHUNK_SIZE {
        for y in 0..CHUNK_SIZE {
            for x in 0..CHUNK_SIZE {
                let pos = Vec3::new(x as f32, y as f32, z as f32);
                let dist = pos.distance(center) - radius;
                sdf.set(x, y, z, dist);
            }
        }
    }

    commands.spawn((Chunk, ChunkPosition(IVec3::ZERO), sdf));
    println!("Spawned sphere SDF chunk at (0, 0, 0)");
}

// --- Main World Controller ---

fn compaction_test_controller(
    shared_state: Res<SharedCompactionState>,
    mut app_exit: MessageWriter<AppExit>,
) {
    let state = shared_state.0.lock().unwrap();

    if state.test_complete {
        println!("\n🎉 PASS 2 STREAM COMPACTION TEST PASSED SUCCESSFULLY!");
        println!(
            "Active surface cells flagged by Pass 1: {}",
            state.active_cell_count
        );
        println!(
            "Max compacted offset index generated by Pass 2: {}",
            state.max_offset
        );
        app_exit.write(AppExit::Success);
    }
}

// --- Render World Pass 2 Verification System ---

fn verify_pass2_compaction_results(
    gpu_buffers_query: Query<(&MainEntity, &GpuVoxelChunkBuffers)>,
    render_device: Res<RenderDevice>,
    render_queue: Res<RenderQueue>,
    shared_state: Res<SharedCompactionState>,
) {
    let mut state = shared_state.0.lock().unwrap();
    if state.test_complete {
        return;
    }

    for (_main_entity, buffers) in gpu_buffers_query.iter() {
        let flags_size = buffers.flags_buffer.size();
        let offsets_size = buffers.compacted_offsets_buffer.size();

        // Staging buffer for flags (Pass 1)
        let staging_flags = render_device.create_buffer(&BufferDescriptor {
            label: Some("flags_readback_staging"),
            size: flags_size,
            usage: BufferUsages::MAP_READ | BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        // Staging buffer for compacted offsets (Pass 2)
        let staging_offsets = render_device.create_buffer(&BufferDescriptor {
            label: Some("offsets_readback_staging"),
            size: offsets_size,
            usage: BufferUsages::MAP_READ | BufferUsages::COPY_DST,
            mapped_at_creation: false,
        });

        let mut encoder = render_device.create_command_encoder(&default());
        encoder.copy_buffer_to_buffer(&buffers.flags_buffer, 0, &staging_flags, 0, flags_size);
        encoder.copy_buffer_to_buffer(
            &buffers.compacted_offsets_buffer,
            0,
            &staging_offsets,
            0,
            offsets_size,
        );
        render_queue.submit(Some(encoder.finish()));

        let flags_slice = staging_flags.slice(..);
        let offsets_slice = staging_offsets.slice(..);

        let (sender_flags, receiver_flags) = std::sync::mpsc::channel();
        let (sender_offsets, receiver_offsets) = std::sync::mpsc::channel();

        flags_slice.map_async(MapMode::Read, move |res| {
            sender_flags.send(res).unwrap();
        });

        offsets_slice.map_async(MapMode::Read, move |res| {
            sender_offsets.send(res).unwrap();
        });

        render_device
            .wgpu_device()
            .poll(PollType::wait_indefinitely());

        if receiver_flags.recv().unwrap().is_ok() && receiver_offsets.recv().unwrap().is_ok() {
            let flags_data = flags_slice.get_mapped_range();
            let flags: &[u32] = bytemuck::cast_slice(&flags_data);
            let active_count = flags.iter().filter(|&&flag| flag > 0).count() as u32;

            let offsets_data = offsets_slice.get_mapped_range();
            let offsets: &[u32] = bytemuck::cast_slice(&offsets_data);

            let max_off = *offsets.iter().max().unwrap_or(&0);

            // Debug print the first few elements to see what Pass 2 is writing
            println!(
                "DEBUG Readback -> Active cells (Pass 1): {}, Max Offset (Pass 2): {}, First 8 offsets: {:?}",
                active_count,
                max_off,
                &offsets[..8.min(offsets.len())]
            );

            if active_count > 0 && max_off > 0 {
                state.active_cell_count = active_count;
                state.max_offset = max_off;
                state.test_complete = true;
            } else {
                println!("⏳ Compute passes not ready yet on this frame, retrying next frame...");
            }
        }

        staging_flags.unmap();
        staging_offsets.unmap();

        if state.test_complete {
            break;
        }
    }
}
